version: '3'
services: 
  phpSite:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:80"
    volumes:
    - ./:/var/www/html/
  dbServer:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  dbadminer:
    image: adminer
    ports:
      - 5001:8080

volumes:
  mysql-data: